INFO 2015-12-13 16:13:20 /test/test.py:739 127.0.0.1 github.com/fanfank ffb034da94c8a3c4c process=240437 thread=139949671794496 data=stream_filter: display_status:96 abcdefghijklmnopqrst 43
OperationalError: (OperationalError) (2013, 'Lost connection to MySQL server during query') 'SELECT XXXXXX HAHAHAHAHA' (38324L, 1, 500) 42
    raise errorclass, errorvalue 41
  File "/test/test.py", line 36, in mosiac_you_cant_see_me 40
    self.errorhandler(self, exc, value) 39
  File "/test/test.py", line 202, in mosiac_you_cant_see_me 38
    cursor.execute(statement, parameters) 37
  File "/test/test.py", line 324, in mosiac_you_cant_see_me 36
    context) 35
  File "/test/test.py", line 867, in mosiac_you_cant_see_me 34
    reraise(type(exception), exception, tb=exc_tb) 33
  File "/test/test.py", line 196, in mosiac_you_cant_see_me 32
    exc_info 31
  File "/test/test.py", line 1024, in mosiac_you_cant_see_me 30
    context) 29
  File "/test/test.py", line 874, in mosiac_you_cant_see_me 28
    compiled_sql, distilled_params 27
  File "/test/test.py", line 761, in mosiac_you_cant_see_me 26
    params) 25
  File "/test/test.py", line 662, in mosiac_you_cant_see_me 24
    result = conn.execute(querycontext.statement, self._params) 23
  File "/test/test.py", line 2381, in mosiac_you_cant_see_me 22
    return self._execute_and_instances(context) 21
  File "/test/test.py", line 2366, in mosiac_you_cant_see_me 20
    .limit(500))]) 19
  File "/test/test.py", line 475, in mosiac_you_cant_see_me 18
    data = self._get(**kwargs) 17
  File "/test/test.py", line 77, in mosiac_you_cant_see_me 16
    media_ids = set(device_like_medias_cache.get(device_id=device_id, cache_only=cache_only) or []) 15
  File "/test/test.py", line 374, in mosiac_you_cant_see_me 14
Traceback (most recent call last): 13
INFO 2015-12-13 15:14:20 /test/test.py:739 127.0.0.1 github.com/fanfank ffb034da94c8a3c4c process=240437 thread=139949671794496 data=stream_filter: display_status:96 abcdefghijklmnopqrst 12
INFO 2015-12-13 15:13:20 /test/test.py:517 127.0.0.1 github.com/fanfank 7da6e5914b97ee879 process=125881 thread=139949671794496 data=www.reetsee.com=15 11
INFO 2015-12-13 15:13:20 /test/test.py:517 127.0.0.1 github.com/fanfank 8acd5a195d8b165e2 process=238577 thread=139949671794496 data=www.reetsee.com=8 10
INFO 2015-12-13 14:13:20 /test/test.py:698 127.0.0.1 github.com/fanfank 7da6e5914b97ee879 process=125881 thread=139949671794496 data=plan feed.items= 15, feed_count: 15, has_more: True, items: [?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?] 9
INFO 2015-12-13 13:14:20 /test/test.py:724 127.0.0.1 github.com/fanfank 5706f9f32b718f0c7 process=242998 thread=139949671794496 data=hello : reetsee_data abcdefghijklmnopqrst 8
INFO 2015-12-13 13:13:20 /test/test.py:724 127.0.0.1 github.com/fanfank 5706f9f32b718f0c7 process=242998 thread=139949671794496 data=hello : reetsee_data abcdefghijklmnopqrst 7
NameError: name 'count' is not defined 6
  File "<stdin>", line 1, in <module> 5
Traceback (most recent call last): 4
INFO 2015-12-13 13:13:20 /test/test.py:724 127.0.0.1 github.com/fanfank 5706f9f32b718f0c7 process=242998 thread=139949671794496 data=hello : reetsee_data abcdefghijklmnopqrst 3
INFO 2015-12-13 12:13:20 /test/test.py:724 127.0.0.1 github.com/fanfank 5706f9f32b718f0c7 process=242998 thread=139949671794496 data=hello : reetsee_data abcdefghijklmnopqrst 2
INFO 2015-12-13 12:13:20 /test/test.py:724 127.0.0.1 github.com/fanfank 5706f9f32b718f0c7 process=242998 thread=139949671794496 data=hello : reetsee_data abcdefghijklmnopqrst 1
